"""Add lead fingerprint for deduplication

Revision ID: 90d989f8827b
Revises: 975cf1764c7d
Create Date: 2026-07-31 20:38:47.683057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d989f8827b'
down_revision: Union[str, Sequence[str], None] = '975cf1764c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_leads_post_url'), table_name='leads')
    op.create_index(op.f('ix_leads_post_url'), 'leads', ['post_url'], unique=False)
    op.create_index(op.f('ix_leads_fingerprint'), 'leads', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_fingerprint'), table_name='leads')
    op.drop_index(op.f('ix_leads_post_url'), table_name='leads')
    op.create_index(op.f('ix_leads_post_url'), 'leads', ['post_url'], unique=1)
    op.drop_column('leads', 'fingerprint')
    # ### end Alembic commands ###
