"""Add job execution expanded status and error categories

Revision ID: a3715de40b7c
Revises: 90d989f8827b
Create Date: 2026-07-31 20:40:41.827152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3715de40b7c'
down_revision: Union[str, Sequence[str], None] = '90d989f8827b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('error_category', sa.Enum('AUTH_FAILED', 'TIMEOUT', 'RATE_LIMITED', 'SELECTOR_CHANGED', 'NETWORK_ERROR', 'UNKNOWN', name='joberrorcategory'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'error_category')
    # ### end Alembic commands ###
